name:                notion-cli
version:             0.1.0.0
github:              "kurubushi/notion-cli-hs"
license:             BSD3
author:              "kurubushi"
maintainer:          "krbshi@gmail.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kurubushi/notion-cli#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1 && < 2
- aeson-casing >= 0 && < 1
- filepath >= 1 && < 2
- text >= 1 && < 2
- bytestring >= 0 && < 1
- http-conduit >= 2 && < 3
- safe-exceptions >= 0 && < 1
- mime-types >= 0 && < 1
- optparse-applicative >= 0 && < 1

library:
  source-dirs: src

executables:
  notion-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-cli

tests:
  notion-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - notion-cli
